import { useState } from 'react'
import { apiClient } from '../../../services/apiClient'
import { useAddLiturgyResource, useAdminLiturgy, useCreateLiturgyCollection, useLiturgyStatus } from '../../../hooks/useCms'

export function LiturgyCmsPage() {
  const { data: collections = [] } = useAdminLiturgy(); const create = useCreateLiturgyCollection(); const status = useLiturgyStatus(); const add = useAddLiturgyResource()
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [resource, setResource] = useState<Record<string, { title: string; description: string; pdf: File | null }>>({})
  async function saveResource(id: string) { const item = resource[id]; if (!item?.title || !item.pdf) return; const fd = new FormData(); fd.append('file', item.pdf); const { data } = await apiClient.post<{ url: string }>('/admin/cms/uploads/pdf', fd); await add.mutateAsync({ id, data: { title: item.title, description: item.description, pdf_url: data.url } }); setResource(old => ({ ...old, [id]: { title: '', description: '', pdf: null } })) }
  return <div><div className="admin-page-header"><div><h1>Liturgy</h1><p>Sections are top-level folders. Resources can only be added inside a section.</p></div></div><form className="admin-form" onSubmit={e => { e.preventDefault(); if (title.trim()) void create.mutateAsync({ title, description }).then(() => { setTitle(''); setDescription('') }) }}><h3>New section</h3><input required value={title} onChange={e => setTitle(e.target.value)} placeholder="Section title" /><textarea value={description} onChange={e => setDescription(e.target.value)} placeholder="Description" /><button className="button button--primary">Save section</button></form>{collections.map(collection => { const item = resource[collection.id] ?? { title: '', description: '', pdf: null }; return <section className="admin-form" key={collection.id}><div className="admin-page-header"><div><h2>{collection.title}</h2><p>{collection.description}</p></div><button type="button" className="button button--outline" onClick={() => void status.mutate({ id: collection.id, action: collection.status === 'PUBLISHED' ? 'unpublish' : 'publish' })}>{collection.status === 'PUBLISHED' ? 'Unpublish' : 'Publish'}</button></div>{collection.resources.map(file => <p key={file.id}><strong>{file.title}</strong> — <a href={file.pdf_url} target="_blank" rel="noreferrer">Open PDF</a></p>)}<h3>Add resource</h3><input value={item.title} onChange={e => setResource(old => ({ ...old, [collection.id]: { ...item, title: e.target.value } }))} placeholder="Title" /><textarea value={item.description} onChange={e => setResource(old => ({ ...old, [collection.id]: { ...item, description: e.target.value } }))} placeholder="Description" /><input type="file" accept="application/pdf" onChange={e => setResource(old => ({ ...old, [collection.id]: { ...item, pdf: e.target.files?.[0] ?? null } }))} /><button type="button" className="button button--primary" onClick={() => void saveResource(collection.id)} disabled={add.isPending}>Save resource</button></section> })}</div>
}
