import { useEffect, useState } from 'react'
import { apiClient } from '../../../services/apiClient'
import { useAddLiturgyResource, useAdminLiturgy, useCreateLiturgyCollection, useLiturgyStatus, useUpdateLiturgyCollection } from '../../../hooks/useCms'

type Draft = { title: string; description: string; pdf: File | null }
export function LiturgyCmsPage() {
  const { data: folders = [] } = useAdminLiturgy(); const create = useCreateLiturgyCollection(); const update = useUpdateLiturgyCollection(); const publish = useLiturgyStatus(); const add = useAddLiturgyResource()
  const [selectedId, setSelectedId] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [folder, setFolder] = useState({ title: '', description: '' }); const [draft, setDraft] = useState<Draft>({ title: '', description: '', pdf: null }); const [dirty, setDirty] = useState(false)
  const selected = folders.find(folder => folder.id === selectedId) ?? folders[0]
  useEffect(() => { if (selected && selected.id !== selectedId) setSelectedId(selected.id) }, [selected, selectedId])
  useEffect(() => { if (selected) { setFolder({ title: selected.title, description: selected.description ?? '' }); setDraft({ title: '', description: '', pdf: null }); setDirty(false) } }, [selected?.id])
  async function save() { if (!selected || !folder.title.trim()) return; await update.mutateAsync({ id: selected.id, data: { title: folder.title, description: folder.description } }); if (draft.title && draft.pdf) { const fd = new FormData(); fd.append('file', draft.pdf); const { data } = await apiClient.post<{ url: string }>('/admin/cms/uploads/pdf', fd); await add.mutateAsync({ id: selected.id, data: { title: draft.title, description: draft.description, pdf_url: data.url } }) }; setDirty(false) }
  return <div className="liturgy-cms"><div className="admin-page-header"><div><h1>Liturgy</h1><p>Create top-level folders and add PDF resources inside them.</p></div><button className="button button--primary" onClick={() => setCreating(true)}>+ New folder</button></div>{creating && <div className="liturgy-cms__new"><input autoFocus placeholder="Folder name" value={folder.title} onChange={e => setFolder({ ...folder, title: e.target.value })}/><textarea placeholder="Folder description" value={folder.description} onChange={e => setFolder({ ...folder, description: e.target.value })}/><button className="button button--primary" onClick={() => void create.mutateAsync(folder).then(item => { setSelectedId(item.id); setCreating(false); setFolder({ title: '', description: '' }) })}>Save folder</button><button className="button button--outline" onClick={() => setCreating(false)}>Cancel</button></div>}<div className="liturgy-cms__layout"><aside className="liturgy-cms__folders"><h2>Folders</h2>{folders.map(item => <button key={item.id} className={`liturgy-cms__folder${item.id === selected?.id ? ' is-selected' : ''}`} onClick={() => setSelectedId(item.id)}>{item.title}<small>{item.resources.length} item{item.resources.length === 1 ? '' : 's'} · {item.status.toLowerCase()}</small></button>)}</aside><section className="liturgy-cms__editor">{selected ? <><div className="liturgy-cms__editor-head"><h2>{selected.title}</h2><div>{dirty && <button className="button button--primary" onClick={() => void save()}>Save changes</button>}<button className="button button--outline" onClick={() => void publish.mutate({ id: selected.id, action: selected.status === 'PUBLISHED' ? 'unpublish' : 'publish' })}>{selected.status === 'PUBLISHED' ? 'Unpublish' : 'Publish'}</button></div></div><label>Name<input value={folder.title} onChange={e => { setFolder({ ...folder, title: e.target.value }); setDirty(true) }}/></label><label>Description<textarea value={folder.description} onChange={e => { setFolder({ ...folder, description: e.target.value }); setDirty(true) }}/></label><div className="liturgy-cms__resources"><h3>Contents</h3>{selected.resources.length ? selected.resources.map(file => <a key={file.id} href={file.pdf_url} target="_blank" rel="noreferrer"><strong>{file.title}</strong><span>{file.description || 'Open PDF'}</span></a>) : <p>This folder has no resources yet.</p>}</div><div className="liturgy-cms__add-resource"><h3>Add PDF resource</h3><input placeholder="Resource title" value={draft.title} onChange={e => { setDraft({ ...draft, title: e.target.value }); setDirty(true) }}/><textarea placeholder="Description" value={draft.description} onChange={e => { setDraft({ ...draft, description: e.target.value }); setDirty(true) }}/><input type="file" accept="application/pdf" onChange={e => { setDraft({ ...draft, pdf: e.target.files?.[0] ?? null }); setDirty(true) }}/><p>Use Save changes above to add this resource.</p></div></> : <p>Create a folder to begin.</p>}</section></div></div>
}
