import { useEffect, useState } from 'react'
import { apiClient } from '../../../services/apiClient'
import { useAddLiturgyResource, useAdminLiturgy, useCreateLiturgyCollection, useLiturgyStatus, useUpdateLiturgyCollection } from '../../../hooks/useCms'

type Draft = { title: string; pdf: File | null }

export function LiturgyCmsPage() {
  const { data: folders = [] } = useAdminLiturgy()
  const create = useCreateLiturgyCollection(); const update = useUpdateLiturgyCollection(); const publish = useLiturgyStatus(); const add = useAddLiturgyResource()
  const [selectedId, setSelectedId] = useState<string | null>(null); const [creating, setCreating] = useState(false); const [newName, setNewName] = useState(''); const [folderName, setFolderName] = useState(''); const [draft, setDraft] = useState<Draft>({ title: '', pdf: null }); const [dirty, setDirty] = useState(false)
  const selected = folders.find(folder => folder.id === selectedId) ?? folders[0]
  useEffect(() => { if (selected && selected.id !== selectedId) setSelectedId(selected.id) }, [selected, selectedId])
  useEffect(() => { if (selected) { setFolderName(selected.title); setDraft({ title: '', pdf: null }); setDirty(false) } }, [selected?.id])
  async function save() { if (!selected || !folderName.trim()) return; await update.mutateAsync({ id: selected.id, data: { title: folderName.trim(), description: '' } }); if (draft.title.trim() && draft.pdf) { const form = new FormData(); form.append('file', draft.pdf); const { data } = await apiClient.post<{ url: string }>('/admin/cms/uploads/pdf', form); await add.mutateAsync({ id: selected.id, data: { title: draft.title.trim(), pdf_url: data.url } }) }; setDirty(false) }
  return <div className="liturgy-cms"><div className="admin-page-header"><div><h1>Liturgy</h1><p>Manage folders and their PDF resources.</p></div><button className="button button--primary" onClick={() => setCreating(true)}>+ New folder</button></div>{creating && <div className="liturgy-cms__new"><input autoFocus placeholder="Folder name" value={newName} onChange={e => setNewName(e.target.value)} /><button className="button button--primary" disabled={!newName.trim()} onClick={() => void create.mutateAsync({ title: newName.trim() }).then(folder => { setSelectedId(folder.id); setNewName(''); setCreating(false) })}>Save folder</button><button className="button button--outline" onClick={() => setCreating(false)}>Cancel</button></div>}<div className="liturgy-cms__layout"><aside className="liturgy-cms__folders"><h2>Folders</h2>{folders.length ? folders.map(folder => <button key={folder.id} className={`liturgy-cms__folder${folder.id === selected?.id ? ' is-selected' : ''}`} onClick={() => setSelectedId(folder.id)}>{folder.title}<small>{folder.resources.length} resource{folder.resources.length === 1 ? '' : 's'}</small></button>) : <p>No folders yet.</p>}</aside><section className="liturgy-cms__editor">{selected ? <><div className="liturgy-cms__editor-head"><h2>{selected.title}</h2><div>{dirty && <button className="button button--primary" onClick={() => void save()} disabled={update.isPending || add.isPending}>Save changes</button>}<button className="button button--outline" onClick={() => void publish.mutate({ id: selected.id, action: selected.status === 'PUBLISHED' ? 'unpublish' : 'publish' })}>{selected.status === 'PUBLISHED' ? 'Unpublish' : 'Publish'}</button></div></div><label>Folder name<input value={folderName} onChange={e => { setFolderName(e.target.value); setDirty(true) }} /></label><div className="liturgy-cms__resources"><h3>Resources</h3>{selected.resources.length ? selected.resources.map(file => <a key={file.id} href={file.pdf_url} target="_blank" rel="noreferrer"><strong>{file.title}</strong><span>Open PDF</span></a>) : <p>This folder has no resources yet.</p>}</div><div className="liturgy-cms__add-resource"><h3>Add resource</h3><input placeholder="Resource name" value={draft.title} onChange={e => { setDraft({ ...draft, title: e.target.value }); setDirty(true) }} /><input type="file" accept="application/pdf" onChange={e => { setDraft({ ...draft, pdf: e.target.files?.[0] ?? null }); setDirty(true) }} /><p>Use Save changes above to add this PDF.</p></div></> : <p>Create a folder to begin.</p>}</section></div></div>
}
