"""create phase four domain foundation

Revision ID: 20260831_0001
Revises:
Create Date: 2026-08-31
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260831_0001"
down_revision = None
branch_labels = None
depends_on = None

def _enum(name, *values):
    # Types are created explicitly below so table creation does not emit duplicates.
    return postgresql.ENUM(*values, name=name, create_type=False)
def _id(): return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False)
def _timestamps(): return [sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)]

def upgrade():
    role = _enum("role_name", "SUPER_ADMIN", "CONTENT_ADMIN", "MEMBER_ADMIN", "TREASURER")
    member_status = _enum("membership_status", "ACTIVE", "INACTIVE", "TRANSFERRED", "DECEASED", "OTHER")
    relationship = _enum("relationship_type", "PARENT", "CHILD", "SPOUSE", "SIBLING", "GUARDIAN", "OTHER")
    due_status = _enum("due_status", "PENDING", "PARTIALLY_PAID", "PAID", "WAIVED", "OVERDUE")
    payment_status = _enum("payment_status", "PENDING", "COMPLETED", "VOID", "FAILED")
    method = _enum("payment_method", "CASH", "BANK_TRANSFER", "ONLINE", "OTHER")
    donation_payment_status = _enum("donation_payment_status", "PENDING", "COMPLETED", "VOID", "FAILED")
    donation_method = _enum("donation_payment_method", "CASH", "BANK_TRANSFER", "ONLINE", "OTHER")
    event_status = _enum("event_status", "DRAFT", "PUBLISHED", "CANCELLED", "COMPLETED")
    announcement_type = _enum("announcement_type", "GENERAL", "IMPORTANT", "COMMUNITY", "FUNERAL", "MARRIAGE", "OTHER")
    announcement_status = _enum("announcement_status", "DRAFT", "PUBLISHED", "ARCHIVED")
    gallery_status = _enum("gallery_album_status", "DRAFT", "PUBLISHED", "ARCHIVED")
    sermon_status = _enum("sermon_status", "DRAFT", "PUBLISHED", "ARCHIVED")
    content_status = _enum("page_content_status", "DRAFT", "PUBLISHED", "ARCHIVED")
    for value in (role, member_status, relationship, due_status, payment_status, method, donation_payment_status, donation_method, event_status, announcement_type, announcement_status, gallery_status, sermon_status, content_status): value.create(op.get_bind(), checkfirst=False)
    op.create_table("roles", _id(), sa.Column("name", role, nullable=False, unique=True), sa.Column("description", sa.Text()), *_timestamps())
    op.create_table("admin_users", _id(), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("auth_subject", sa.String(255), nullable=False, unique=True), sa.Column("role_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roles.id", ondelete="RESTRICT"), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("last_login_at", sa.DateTime(timezone=True)), *_timestamps()); op.create_index("ix_admin_users_email", "admin_users", ["email"])
    op.create_table("families", _id(), sa.Column("family_name", sa.String(200), nullable=False), sa.Column("address", sa.Text()), sa.Column("notes", sa.Text()), *_timestamps()); op.create_index("ix_families_family_name", "families", ["family_name"])
    op.create_table("members", _id(), sa.Column("first_name", sa.String(100), nullable=False), sa.Column("middle_name", sa.String(100)), sa.Column("last_name", sa.String(100), nullable=False), sa.Column("date_of_birth", sa.Date()), sa.Column("phone", sa.String(50)), sa.Column("email", sa.String(320)), sa.Column("address", sa.Text()), sa.Column("photo_url", sa.String(2048)), sa.Column("membership_status", member_status, nullable=False), sa.Column("date_joined", sa.Date()), sa.Column("notes", sa.Text()), sa.Column("family_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("families.id", ondelete="SET NULL")), *_timestamps()); op.create_index("ix_members_email", "members", ["email"]); op.create_index("ix_members_family_id", "members", ["family_id"]); op.create_index("ix_members_membership_status", "members", ["membership_status"])
    op.create_table("member_relationships", _id(), sa.Column("member_a_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("members.id", ondelete="RESTRICT"), nullable=False), sa.Column("relationship_type", relationship, nullable=False), sa.Column("member_b_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("members.id", ondelete="RESTRICT"), nullable=False), *_timestamps(), sa.UniqueConstraint("member_a_id", "relationship_type", "member_b_id", name="uq_member_relationship"), sa.CheckConstraint("member_a_id <> member_b_id", name="ck_relationship_distinct_members"))
    op.create_table("dues", _id(), sa.Column("member_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("members.id", ondelete="RESTRICT")), sa.Column("family_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("families.id", ondelete="RESTRICT")), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.Text()), sa.Column("amount", sa.Numeric(12,2), nullable=False), sa.Column("due_date", sa.Date()), sa.Column("status", due_status, nullable=False), *_timestamps(), sa.CheckConstraint("amount >= 0", name="ck_due_nonnegative_amount"), sa.CheckConstraint("member_id IS NOT NULL OR family_id IS NOT NULL", name="ck_due_owner")); op.create_index("ix_dues_member_id", "dues", ["member_id"]); op.create_index("ix_dues_family_id", "dues", ["family_id"]); op.create_index("ix_dues_status", "dues", ["status"])
    op.create_table("payments", _id(), sa.Column("member_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("members.id", ondelete="RESTRICT"), nullable=False), sa.Column("due_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("dues.id", ondelete="RESTRICT")), sa.Column("amount", sa.Numeric(12,2), nullable=False), sa.Column("payment_date", sa.DateTime(timezone=True), nullable=False), sa.Column("payment_method", method, nullable=False), sa.Column("reference", sa.String(255)), sa.Column("status", payment_status, nullable=False), sa.Column("notes", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.CheckConstraint("amount > 0", name="ck_payment_positive_amount")); op.create_index("ix_payments_member_id", "payments", ["member_id"]); op.create_index("ix_payments_due_id", "payments", ["due_id"]); op.create_index("ix_payments_reference", "payments", ["reference"])
    op.create_table("donations", _id(), sa.Column("donor_name", sa.String(200)), sa.Column("donor_email", sa.String(320)), sa.Column("amount", sa.Numeric(12,2), nullable=False), sa.Column("purpose", sa.String(200)), sa.Column("payment_status", donation_payment_status, nullable=False), sa.Column("payment_method", donation_method), sa.Column("transaction_reference", sa.String(255)), sa.Column("donated_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.CheckConstraint("amount > 0", name="ck_donation_positive_amount")); op.create_index("ix_donations_transaction_reference", "donations", ["transaction_reference"])
    op.create_table("events", _id(), sa.Column("title", sa.String(250), nullable=False), sa.Column("slug", sa.String(250), nullable=False, unique=True), sa.Column("description", sa.Text()), sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False), sa.Column("end_datetime", sa.DateTime(timezone=True)), sa.Column("location", sa.String(250)), sa.Column("image_url", sa.String(2048)), sa.Column("category", sa.String(100)), sa.Column("status", event_status, nullable=False), *_timestamps()); op.create_index("ix_events_slug", "events", ["slug"]); op.create_index("ix_events_start_datetime", "events", ["start_datetime"]); op.create_index("ix_events_category", "events", ["category"])
    op.create_table("announcements", _id(), sa.Column("title", sa.String(250), nullable=False), sa.Column("slug", sa.String(250), nullable=False, unique=True), sa.Column("description", sa.Text()), sa.Column("type", announcement_type, nullable=False), sa.Column("image_url", sa.String(2048)), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("status", announcement_status, nullable=False), *_timestamps()); op.create_index("ix_announcements_slug", "announcements", ["slug"]); op.create_index("ix_announcements_type", "announcements", ["type"]); op.create_index("ix_announcements_published_at", "announcements", ["published_at"])
    op.create_table("gallery_albums", _id(), sa.Column("title", sa.String(250), nullable=False), sa.Column("description", sa.Text()), sa.Column("cover_image_url", sa.String(2048)), sa.Column("status", gallery_status, nullable=False), *_timestamps())
    op.create_table("gallery_images", _id(), sa.Column("album_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("gallery_albums.id", ondelete="CASCADE"), nullable=False), sa.Column("image_url", sa.String(2048), nullable=False), sa.Column("alt_text", sa.String(500), nullable=False), sa.Column("caption", sa.Text()), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("album_id", "sort_order", name="uq_gallery_image_sort_order"))
    op.create_table("sermon_series", _id(), sa.Column("title", sa.String(250), nullable=False, unique=True), sa.Column("description", sa.Text()), *_timestamps())
    op.create_table("sermons", _id(), sa.Column("series_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sermon_series.id", ondelete="SET NULL")), sa.Column("title", sa.String(250), nullable=False), sa.Column("slug", sa.String(250), nullable=False, unique=True), sa.Column("speaker_name", sa.String(200)), sa.Column("date", sa.Date(), nullable=False), sa.Column("scripture_reference", sa.String(500)), sa.Column("description", sa.Text()), sa.Column("video_url", sa.String(2048)), sa.Column("thumbnail_url", sa.String(2048)), sa.Column("status", sermon_status, nullable=False), *_timestamps()); op.create_index("ix_sermons_slug", "sermons", ["slug"]); op.create_index("ix_sermons_series_id", "sermons", ["series_id"]); op.create_index("ix_sermons_date", "sermons", ["date"])
    op.create_table("page_content", _id(), sa.Column("page", sa.String(100), nullable=False), sa.Column("section", sa.String(100), nullable=False), sa.Column("heading", sa.String(300)), sa.Column("body", sa.Text()), sa.Column("image_url", sa.String(2048)), sa.Column("status", content_status, nullable=False), *_timestamps(), sa.UniqueConstraint("page", "section", name="uq_page_content_section"))
    op.create_table("site_settings", _id(), sa.Column("key", sa.String(100), nullable=False, unique=True), sa.Column("value", sa.Text(), nullable=False), sa.Column("is_public", sa.Boolean(), nullable=False), *_timestamps())
    op.create_table("service_times", _id(), sa.Column("day_of_week", sa.Integer(), nullable=False), sa.Column("start_time", sa.Time(), nullable=False), sa.Column("end_time", sa.Time()), sa.Column("service_name", sa.String(200), nullable=False), sa.Column("location", sa.String(250)), sa.Column("description", sa.Text()), sa.Column("is_active", sa.Boolean(), nullable=False), *_timestamps(), sa.CheckConstraint("day_of_week BETWEEN 0 AND 6", name="ck_service_time_day"))

def downgrade():
    # Dependent tables first; PostgreSQL enum types are then removed explicitly.
    for table in ("service_times", "site_settings", "page_content", "sermons", "sermon_series", "gallery_images", "gallery_albums", "announcements", "events", "donations", "payments", "dues", "member_relationships", "members", "families", "admin_users", "roles"): op.drop_table(table)
    for name in ("page_content_status", "sermon_status", "gallery_album_status", "announcement_status", "announcement_type", "event_status", "donation_payment_method", "donation_payment_status", "payment_method", "payment_status", "due_status", "relationship_type", "membership_status", "role_name"): sa.Enum(name=name).drop(op.get_bind(), checkfirst=False)
