import { Link } from 'react-router-dom'
import { Container } from '../../components/ui/Container'
import { Reveal } from '../../components/animation/Reveal'
import { ministryPreviews, serviceTimes, upcomingEvents } from '../../data/siteContent'

export function HomePage() { return <>
  <section className="hero"><div className="hero__art" aria-hidden="true" /><Container className="hero__content"><Reveal><p className="eyebrow">A place to belong</p><h1 className="display">Faith, family, and a warm welcome.</h1><p className="lede">St. Anthony's Malankara Catholic Church is preparing a home online for prayer, community, and parish life.</p><div className="actions"><Link className="button button--light" to="/about">Discover our parish <span aria-hidden="true">↗</span></Link><Link className="button button--outline" to="/contact">Plan a visit</Link></div><p className="hero__note">A visual placeholder for future church photography</p></Reveal></Container></section>
  <section className="schedule"><Container><div className="schedule__panel"><div className="schedule__intro"><p className="eyebrow">Gather with us</p><h2>Service times</h2></div><div className="schedule__list">{serviceTimes.map(item => <div className="schedule__item" key={item.day}><p>{item.day}</p><strong>{item.time}</strong><p>{item.name} · {item.location}</p></div>)}</div></div></Container></section>
  <section className="section"><Container className="intro-grid"><Reveal><p className="eyebrow">Welcome</p><h2 className="heading">A community shaped by prayer and presence.</h2></Reveal><Reveal delay={.1}><p className="lede">This is a visual prototype for the parish's future public website. It is designed to make room for real stories, current ministry information, and the everyday moments that bring a church community together.</p><Link className="text-link" to="/about">Learn about our parish <span aria-hidden="true">→</span></Link></Reveal></Container></section>
  <section className="section--tight"><Container><Reveal><div className="photo-placeholder feature-image" role="img" aria-label="Placeholder for a church interior or community photograph" /></Reveal></Container></section>
  <section className="section"><Container><div className="section-head"><div><p className="eyebrow">What’s ahead</p><h2 className="heading">Gatherings to look forward to.</h2></div><Link className="text-link" to="/events">View all events <span aria-hidden="true">→</span></Link></div><div className="event-grid">{upcomingEvents.map((event, index) => <Reveal key={event.title} delay={index * .07}><article className="event"><span className="event__date">{event.date}</span><h3>{event.title}</h3><p>{event.detail}</p><Link className="text-link" to="/events">Details <span aria-hidden="true">→</span></Link></article></Reveal>)}</div></Container></section>
  <section className="section--tight"><Container><Reveal><article className="sermon"><div className="sermon__art photo-placeholder" role="img" aria-label="Placeholder for sermon artwork or church photograph" /><div className="sermon__body"><p className="eyebrow">Latest message</p><h2 className="heading">Messages that meet us where we are.</h2><p>Future homilies, reflections, and recordings will live here, ready to share with parishioners and visitors alike.</p><Link className="button button--light" to="/sermons">Explore messages <span aria-hidden="true">↗</span></Link></div></article></Reveal></Container></section>
  <section className="section ministries"><Container><div className="section-head"><div><p className="eyebrow">Parish life</p><h2 className="heading">Many ways to grow together.</h2></div><Link className="text-link" to="/ministries">Explore ministries <span aria-hidden="true">→</span></Link></div><div className="ministry-grid">{ministryPreviews.map((ministry, index) => <Reveal key={ministry.number} delay={index * .07}><article className="ministry"><span>{ministry.number}</span><h3>{ministry.title}</h3><p>{ministry.detail}</p></article></Reveal>)}</div></Container></section>
  <section className="section"><Container><div className="section-head"><div><p className="eyebrow">Our community</p><h2 className="heading">The beauty of being together.</h2></div><Link className="text-link" to="/gallery">View gallery <span aria-hidden="true">→</span></Link></div><Reveal><div className="gallery" aria-label="Three placeholders for future parish photographs"><div className="photo-placeholder" /><div className="photo-placeholder" /><div className="photo-placeholder" /></div></Reveal></Container></section>
  <section className="section--tight"><Container><article className="visit"><div className="visit__map" role="img" aria-label="Location placeholder" /><div className="visit__body"><p className="eyebrow">Find your way</p><h2 className="heading heading--small">Come as you are.</h2><p>Practical visitor information, directions, and accessible service details will be shared here when the parish confirms them.</p><Link className="text-link" to="/contact">Plan your visit <span aria-hidden="true">→</span></Link></div></article></Container></section>
  <section className="section cta"><Container><Reveal><p className="eyebrow" style={{ color: '#fff' }}>Stay connected</p><h2 className="heading">There is a place for you here.</h2><p>Explore the parish, find a service, or get in touch as we prepare this online home.</p><div className="actions"><Link className="button button--light" to="/contact">Contact the parish <span aria-hidden="true">↗</span></Link></div></Reveal></Container></section>
</> }
